DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  user_id INT AUTO_INCREMENT  PRIMARY KEY,
  user_key VARCHAR(20) NOT NULL,
  user_name VARCHAR(100) NOT NULL,
  user_gender VARCHAR(20) DEFAULT NULL,
  korean OTHER NOT NULL
);

DROP TABLE IF EXISTS KOREAN;

CREATE TABLE KOREAN (
  korean_id INT AUTO_INCREMENT  PRIMARY KEY,
  korean_key VARCHAR(20) NOT NULL,
  korean_name VARCHAR(100) NOT NULL,
  korean_pronounce VARCHAR(100) NOT NULL,
  korean_gender VARCHAR(20) DEFAULT NULL
);